/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist/index'
import { Route as StocksIndexRouteImport } from './routes/stocks/index'
import { Route as StocksSymbolRouteImport } from './routes/stocks/$symbol'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksIndexRoute = StocksIndexRouteImport.update({
  id: '/stocks/',
  path: '/stocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/not-found': typeof NotFoundRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks': typeof StocksIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/not-found': typeof NotFoundRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks': typeof StocksIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/not-found': typeof NotFoundRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks/': typeof StocksIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/not-found' | '/stocks/$symbol' | '/stocks' | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/not-found' | '/stocks/$symbol' | '/stocks' | '/watchlist'
  id: '__root__' | '/' | '/auth' | '/not-found' | '/stocks/$symbol' | '/stocks/' | '/watchlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NotFoundRoute: typeof NotFoundRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
  StocksIndexRoute: typeof StocksIndexRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/': {
      id: '/stocks/'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NotFoundRoute: NotFoundRoute,
  StocksSymbolRoute: StocksSymbolRoute,
  StocksIndexRoute: StocksIndexRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
